services:
  mariadb:
    image: mariadb:lts-noble
    container_name: qoin-db
    volumes:
      - ./task1/src/database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=qoin-db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: qoin-mq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
